version: '3.9'
services:
  postgresdb:
    image: postgres:16.3-alpine
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
      - DATABASE_HOST=${POSTGRES_HOST}
    ports:
      - '4568:5432'
    volumes:
      - ./../.pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./../.redis:/root/redis
      - ./../.redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=OJocasd923sa0d4
      - REDIS_PORT=6379
      - REDIS_DATABASES=0


  botmanager:
    build: .
    ports:
      - "8080:8080"
    restart: always

volumes:
  pg_data: